#ifndef _MEDIATYPE_H_
#define _MEDIATYPE_H_

typedef enum
{
	MEDIA_TYPE_UNKNOWN,
	MEDIA_TYPE_UNKNOWN_AUDIO,
	MEDIA_TYPE_UNKNOWN_VIDEO,
	MEDIA_TYPE_3GPP,
	MEDIA_TYPE_AAC,
	MEDIA_TYPE_AC3,
	MEDIA_TYPE_AIFF,
	MEDIA_TYPE_AMR,
	MEDIA_TYPE_ASF,
	MEDIA_TYPE_AU,
	MEDIA_TYPE_AVI,
	MEDIA_TYPE_BITMAP,
	MEDIA_TYPE_DAT,
	MEDIA_TYPE_DDPLUS,
	MEDIA_TYPE_DTS,
	MEDIA_TYPE_DVR,
	MEDIA_TYPE_FLAC,
	MEDIA_TYPE_FLASHVIDEO,
	MEDIA_TYPE_H264,
	MEDIA_TYPE_MATROSKA,
	MEDIA_TYPE_MIDI,
	MEDIA_TYPE_MIDIEVENT,
	MEDIA_TYPE_MJPEG,
	MEDIA_TYPE_MLP,
	MEDIA_TYPE_MONKEYSAUDIO,
	MEDIA_TYPE_MPEG4,
	MEDIA_TYPE_MPEG4VIDEO,
	MEDIA_TYPE_MPEGAUDIO,
	MEDIA_TYPE_MPEGPROGRAM,
	MEDIA_TYPE_MPEGTRANSPORT,
	MEDIA_TYPE_MPEGVIDEO,
	MEDIA_TYPE_OGG,
	MEDIA_TYPE_PCM,
	MEDIA_TYPE_PESPACKET,
	MEDIA_TYPE_PNG,
	MEDIA_TYPE_PROGRAMASSOCIATION,
	MEDIA_TYPE_PROGRAMMAP,
	MEDIA_TYPE_QUICKTIME,
	MEDIA_TYPE_REALAUDIO,
	MEDIA_TYPE_REALMEDIA,
	MEDIA_TYPE_RMID,
	MEDIA_TYPE_SUBPICTURE,
	MEDIA_TYPE_THEORA,
	MEDIA_TYPE_VC1,
	MEDIA_TYPE_VORBIS,
	MEDIA_TYPE_WAV,
	MEDIA_TYPE_WMA,
	MEDIA_TYPE_WMV,
	MEDIA_TYPE_NUM
} MediaType;

typedef enum
{
	RENDER_TYPE_UNKNOWN,
	RENDER_TYPE_AUDIO,
	RENDER_TYPE_VIDEO,
	RENDER_TYPE_SPDIF,
	RENDER_TYPE_MIDI,
	RENDER_TYPE_FILE,
	RENDER_TYPE_TEXT,
	RENDER_TYPE_NUM
} RenderType;

#endif
